### ISSUE TITLE
Run Puerto Rico through Whisper x2

### ISSUE THREAD

**Issue by ekemeyer** [WGBH-MLA/whisper-bot#2]
### Because

We need files from Puerto Rico run through Whisper, once for English, once for Spanish. This was a deliverable in the Puerto Rico grant.

### Done when

Puerto Rico transcripts are available for QC

### Additional context
Owen pinged Kevin on this May 8th with files to run
_No response_

**Comment by foo4thought** [comment]
ASR process completed for initial batch of 1500; transcript metadata is updated on ams2; assets are reindexed on AAPB; successful outcomes verified and workflow fully documented in database AAPB_Enhancement.

NOTE:  2195 more assets have been added to the job and have begun ASR processing

**Comment by ekemeyer** [comment]
All WIPR records requested have been run
